### ISSUE TITLE
"Mindmap" option does not appear in the Add node context menu despite already installed.

### ISSUE THREAD

**Issue by Potato22** [SpectralVectors/MindMapper#6]
![image](https://user-images.githubusercontent.com/39096741/143864712-6b9be875-25ba-447b-aa38-48a050090235.png)
![image](https://user-images.githubusercontent.com/39096741/143864800-a1056813-e09c-4fc7-a4fc-9ba4d3ce60f8.png)
The plugin is visible, listed, and enabled but doesn't seem like it's working.

Any help is appreciated.
Blender 2.93.1
Windows 11 Pro for Workstations 64bit

**Comment by SpectralVectors** [comment]
Hi Potato, it looks like you're in the Shader Node Editor, MindMapper is actually a custom Node **Editor** type, not a custom **Node** type, so, to access it you have to click on the top left corner of the screen to get the editor type dropdown (the one with: 3D Viewport, Image Editor... Timeline...Text Editor... Outliner), on my system it shows up between UV Editor and Compositor under the General section.
I'm going to leave this issue open, since it's probably a common misconception, and it seems like it would be a handy thing to have.
It's been long enough since I worked on this that I can't quite remember why I didn't/couldn't add it to the Shader Node menu, I feel like there was some technical reason that prevented it, but I'd have to dive back into the API to be sure.

**Comment by Potato22** [comment]
I see, thank you for clarifying! I see it now and it works properly. Thank you for your time and effort in making this custom addon.

**Comment by SpectralVectors** [comment]
Hi Potato22, your suggestion/issue has been implemented: Mindmap nodes are now available in all Node Editors under the 'Extra' menu, as well as being available in the custom node editor type.
Thanks for using the addon, and creating the issue, I think a lot of users had the same assumption as you, and I'm happy to report that it now works the way you thought!

**Comment by Potato22** [comment]
I'm honored! Now that's convenience, thank you so much!
